version: '3.1'

services:

  springboot:
    image: javamongo.jar
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/workshop_mongo?authSource=admin
    container_name: javamongo
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge
